# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia solution
COPY FCGUserApi.sln ./

# Copia os arquivos .csproj para os caminhos esperados pelo .sln
COPY Adapters/Drivers/FCGUser.Api/FCGUser.Api.csproj ./src/FCGUser.Api/
COPY Core/FCGUser.Application/FCGUser.Application.csproj ./src/FCGUser.Application/
COPY Core/FCGUser.Domain/FCGUser.Domain.csproj ./src/FCGUser.Domain/
COPY Adapters/Driven/FCGUser.Infra/FCGUser.Infra.csproj ./src/FCGUser.Infra/


# Restaura dependências (agora os caminhos batem)
RUN dotnet restore FCGUserApi.sln

# Publica a API
RUN dotnet publish src/Adapters/Drivers/FCGUser.Api/FCGUser.Api.csproj -c Release -o /app/publish

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish ./
ENTRYPOINT ["dotnet", "FCGUser.Api.dll"]
